//! C API bindings for HarfBuzz.
//!
//! Zig 0.17 removed `@cImport`, so these bindings are generated by
//! `zig translate-c` from the system HarfBuzz headers (14.1.0):
//!
//!   zig translate-c -I/usr/include/harfbuzz -I/usr/include/freetype2 \
//!       -I/usr/include -I/usr/include/libpng16 <hb.h + hb-ft.h> \
//!       > src/harfbuzz/c_bindings.zig
//!
//! `c_bindings.zig` keeps the translated types and constants, but its
//! `pub extern fn` entry points would force a link-time dependency on
//! libharfbuzz. `c_bindings_dyn.zig` is the checked-in generated twin
//! (`tools/gen_dyn_bindings.py`) that declares every entry point as a
//! function-pointer variable and resolves the ones this port uses through
//! `dyn.ensureLoaded` / `loadDynamic` at runtime.
//!
//! The library code in this directory (`buffer.zig`, `font.zig`, ...) refers
//! to `c.hb_*` names exactly as the original `@cImport` version did.
pub const c = @import("c_bindings_dyn.zig");
