//! C API bindings for FreeType.
//!
//! Zig 0.17 removed `@cImport`, so these bindings are generated by
//! `zig translate-c` from the system FreeType headers (2.14.3):
//!
//!   zig translate-c -I/usr/include/freetype2 -I/usr/include \
//!       -I/usr/include/libpng16 <ft2build.h + FT_* includes> \
//!       > src/freetype/c_bindings.zig
//!
//! `c_bindings.zig` keeps the translated types and constants, but its
//! `pub extern fn` entry points would force a link-time dependency on
//! libfreetype. `c_bindings_dyn.zig` is the checked-in generated twin
//! (`tools/gen_dyn_bindings.py`) that declares every entry point as a
//! function-pointer variable and resolves the ones this port uses through
//! `dyn.ensureLoaded` / `loadDynamic` at runtime.
//!
//! The library code in this directory (`Library.zig`, `face.zig`, ...) refers
//! to `c.FT_*` names exactly as the original `@cImport` version did.
pub const c = @import("c_bindings_dyn.zig");
